baseURL = "https://cheshire.io/"
languageCode = "en-us"
title = "Cheshire"
theme = "ink"
copyright = "© 2020 Victor Neo. Licensed under CC BY-NC International License."
summaryLength = 4

[params]
	subtitle = "Victor's Writings"

        avatar = "images/profile.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto"
	customCSS = "css/custom.css"
	customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.

[markup]
  defaultMarkdownHandler = "blackFriday"
  [markup.blackFriday]
    hrefTargetBlank = true

[[menu.main]]
name = "All Posts"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/victorneo"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/victorneo"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
